#!/bin/bash
ls -l
[Got]
total 24
-rw-r--r-- 1 996 992 16 0-current_working_directory
-rw-r--r-- 1 996 992 15 1-listit
-rw-r--r-- 1 996 992 15 2-bring_me_home
-rwxr-xr-x 1 996 992 18 3-listfiles
-rw-r--r-- 1 996 992 19 4-listmorefiles
-rw-r--r-- 1 996 992 21 README.md

(244 chars long)

[Expected]
total 24
-rw-r--r-- 1 996 992 16 0-current_working_directory
-rw-r--r-- 1 996 992 15 1-listit
-rw-r--r-- 1 996 992 15 2-bring_me_home
-rw-r--r-- 1 996 992 18 3-listfiles
-rw-r--r-- 1 996 992 19 4-listmorefiles
-rw-r--r-- 1 996 992 21 README.md

(244 chars long)
